
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
    npm run test-ci   
    ls /coverage
    ls     
  displayName: 'npm install, unitTest and build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'sebas6612'
    scannerMode: 'MSBuild'
    projectKey: 'pet-book-s'
    projectName: 'pet-book-s'
    
- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'