trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod  
  displayName: 'npm install and build'

- script: |
    npm run test-ci   
    ls /coverage
    ls
  displayName: 'Run Tests'  

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'sebas6612'
    scannerMode: 'CLI'
    configMode: 'file'
    
- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: Docker@2
  displayName: Login to Docker
  inputs:
    command: login
    containerRegistry: 'azure-devops-docker-hub'
- task: Docker@2
  displayName: 'Build the Docker image and push'
  inputs:
    containerRegistry: 'azure-devops-docker-hub'
    repository: 'sebas6612/pet-book-s'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'Azure-DevOps'

- task: PublishBuildArtifacts@1